package Pack;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class UserPanel extends javax.swing.JFrame {

  Connection_DB Con_DB = new Connection_DB();  
  UserFinds AdFinds = new UserFinds(); 
  UserPeopleList AP_List = new UserPeopleList();
  String SQL;  
    
    
    
        public UserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ProjectText = new javax.swing.JTextField();
        ProjectProgress = new javax.swing.JComboBox<>();
        FindS = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NameText = new javax.swing.JComboBox<>();
        StatusText = new javax.swing.JComboBox<>();
        Tema_Project = new javax.swing.JTextField();
        Tip_Project = new javax.swing.JComboBox<>();
        Priory_Project = new javax.swing.JComboBox<>();
        Opisanie = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        Aunt = new javax.swing.JMenuItem();
        AllPeople = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Панель администратора");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Имя сотрудника");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Должность");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Проект");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Стадия проекта");

        ProjectProgress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Разработка проекта", "Тестирование", "Правка ошибок", "Финальное тестирование", "Проект завершен" }));

        FindS.setText("Найти");
        FindS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindSActionPerformed(evt);
            }
        });

        Clean.setText("Очистить");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Тема проекта");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Тип проекта");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Приоритет проекта");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Описание проекта");

        NameText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        StatusText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        Tip_Project.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Разработка кроссплатформенное ПО", "Разработка приложения под \"OS Windows\"", "Разработка приложения под \"OS Linux\"", "Разработка приложения под \"Mac OS\"", "Разработка приложения под \"OS Android\"", "Разработка сайта" }));

        Priory_Project.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Без срочно", "Низкий ", "Средний ", "Высокйи", "Срочно" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProjectText, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tema_Project, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tip_Project, 0, 285, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(Priory_Project, 0, 285, Short.MAX_VALUE)))
                            .addComponent(FindS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(ProjectProgress, 0, 285, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Opisanie))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NameText, jLabel1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {StatusText, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ProjectText, jLabel3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tema_Project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tip_Project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Priory_Project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opisanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        FileMenu.setText("Файл");

        Aunt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Aunt.setText("Аунтификация");
        Aunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuntActionPerformed(evt);
            }
        });
        FileMenu.add(Aunt);

        AllPeople.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AllPeople.setText("Список всех сотрудников");
        AllPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllPeopleActionPerformed(evt);
            }
        });
        FileMenu.add(AllPeople);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        setSize(1195, 270);
        ReFindUserS();
        FindUserS();        
        Clean_FIND_Data();        
    }//GEN-LAST:event_formWindowOpened

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        Clean_FIND_Data();
    }//GEN-LAST:event_CleanActionPerformed

    private void FindSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindSActionPerformed
        FindS();
    }//GEN-LAST:event_FindSActionPerformed

    private void AllPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllPeopleActionPerformed
        AP_List.CleanTable();
        AP_List.Show_User();
        AP_List.setVisible(true);
    }//GEN-LAST:event_AllPeopleActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
    if (NameText.getSelectedItem().equals(" ")) {            
        } else {
        String SQLPeople = "SELECT * FROM \"PUBLIC\".AUNT where lower(\"NAME\") like lower('%"+NameText.getSelectedItem().toString()+"%')";
        Con_DB.SQL = SQLPeople;
        Con_DB.Connect();
      try {
          Con_DB.RS.next();
          StatusText.setSelectedItem(Con_DB.RS.getString("STATUS"));          
      } catch (SQLException ex) {
          Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
      }
        }
    }//GEN-LAST:event_NameTextActionPerformed

    private void AuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuntActionPerformed
        dispose();
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_AuntActionPerformed

    public void FindS() {
        SQL = "SELECT * FROM \"PUBLIC\".SOFTCORPARATION where ";
        
        String NAME=NameText.getSelectedItem().toString(),
                STATUS=StatusText.getSelectedItem().toString(),
                PROJECT=ProjectText.getText(),
                S_PROJECT=ProjectProgress.getSelectedItem().toString(),                
                TEMA_Project=Tema_Project.getText(),
                tip_Project=Tip_Project.getSelectedItem().toString(),
                project_Priory=Priory_Project.getSelectedItem().toString(),
                opisanie=Opisanie.getText();
        
        
        int Izm_SQL = 0;
        if (NAME.equals(" ")) {
            SQL = "SELECT * FROM \"PUBLIC\".SOFTCORPARATION ";            
        } else {
            SQL = SQL + "lower(NAME) like lower('%"+NAME+"%') ";
            Izm_SQL = 1;
        }
        
        if (STATUS.equals(" ")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(STATUS) like lower('%"+STATUS+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(STATUS) like lower('%"+STATUS+"%') ";
            }
        }
        
        if (PROJECT.equals("")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(PROJECT) like lower('%"+PROJECT+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(PROJECT) like lower('%"+PROJECT+"%') ";
            }
        }
        
        if (TEMA_Project.equals("")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(PROJECT_TEMA) like lower('%"+TEMA_Project+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(PROJECT_TEMA) like lower('%"+TEMA_Project+"%') ";
            }
        }
        
        if (tip_Project.equals(" ")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(PROJECT_TIP) like lower('%"+tip_Project+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(PROJECT_TIP) like lower('%"+tip_Project+"%') ";
            }
        }
        
        if (project_Priory.equals(" ")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(PROJECT_PRIORY) like lower('%"+project_Priory+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(PROJECT_PRIORY) like lower('%"+project_Priory+"%') ";
            }
        }
        
        if (S_PROJECT.equals(" ")) {                  
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(PROJECTSTATUS) like lower('%"+S_PROJECT+"%') ";
            } else {
                SQL = SQL + "and lower(PROJECTSTATUS) like lower('%"+STATUS+"%') ";
            }
        }
        
        if (opisanie.equals("")) {            
        } else {
            if (Izm_SQL == 0) {
                SQL = SQL + "where lower(OPISANIE) like lower('%"+opisanie+"%') ";
                Izm_SQL = 1;
            } else {
                SQL = SQL + "and lower(OPISANIE) like lower('%"+opisanie+"%') ";
            }
        }
        
        Con_DB.SQL = SQL;
        AdFinds.SQL = SQL;
        Con_DB.Connect();
        AdFinds.CleanTable();
        AdFinds.Show_User();
        AdFinds.setVisible(true);  
        
        
    } 
    
    private void Clean_FIND_Data() {
        NameText.setSelectedItem(" ");
        StatusText.setSelectedItem(" ");
        ProjectText.setText("");
        Tema_Project.setText("");
        Tip_Project.setSelectedItem(" ");
        Priory_Project.setSelectedItem(" ");
        ProjectProgress.setSelectedItem(" ");
        Opisanie.setText("");
        AdFinds.CleanTable();        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AllPeople;
    private javax.swing.JMenuItem Aunt;
    private javax.swing.JButton Clean;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton FindS;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JComboBox<String> NameText;
    private javax.swing.JTextField Opisanie;
    private javax.swing.JComboBox<String> Priory_Project;
    private javax.swing.JComboBox<String> ProjectProgress;
    private javax.swing.JTextField ProjectText;
    private javax.swing.JComboBox<String> StatusText;
    private javax.swing.JTextField Tema_Project;
    private javax.swing.JComboBox<String> Tip_Project;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void FindUserS() {
        Con_DB.SQL = "SELECT * FROM \"PUBLIC\".AUNT"; 
        Con_DB.Connect();        
        try {
            while (Con_DB.RS.next()) {                
                NameText.addItem(Con_DB.RS.getString("name"));
                StatusText.addItem(Con_DB.RS.getString("Status"));
            }
        } catch (SQLException e) {
            System.out.println("Ошибка чтения базы данных!");
            JOptionPane.showMessageDialog(null, "Ошибка чтения базы данных!");
        }
        
    }

    private void ReFindUserS() {
        DefaultComboBoxModel comboCleanName = new DefaultComboBoxModel();
        DefaultComboBoxModel comboCleanStatus = new DefaultComboBoxModel();
        NameText.setModel(comboCleanName);
        NameText.addItem(" ");
        StatusText.setModel(comboCleanStatus);
        StatusText.addItem(" ");
        StatusText.addItem("Руководитель отделения");
        StatusText.addItem("Руководитель проекта");
        StatusText.addItem("Старший сотрудник");
        StatusText.addItem("Младший сотрудник");
        StatusText.addItem("Стажер");
    }
    
}
